// src/lib/practices.js
// ─────────────────────────────────────────────────────────────────────────────
// Held micro-practice library — static content, AI-surfaced.
//
// All practices are Manu's methodology: somatic, attachment-informed,
// nervous-system-first. Nothing is generated by AI — selection is.
//
// Structure:
//   PRACTICES        — full library, tagged by category + surface
//   getPractice()    — deterministic daily selector (by surface + date + state)
//   getLogPractice() — reactive selector triggered by what was just logged
//
// Surfaces:
//   "morning"    — Before 10am, body-first grounding
//   "invitation" — 10am–8pm, observational / curious
//   "evening"    — After 8pm, slowing down / closing the loop
//   "log_hard"   — After logging something difficult
//   "log_good"   — After logging a win or positive moment
//
// NS States (from regulation_checkins):
//   "overwhelmed" | "activated" | "shutdown" | "regulated" | null
// ─────────────────────────────────────────────────────────────────────────────

// ─── MORNING PRACTICES ───────────────────────────────────────────────────────
// Body-first. They just woke up. One small thing before the day takes over.

const MORNING = [
  // 🌿 Grounding in the Moment
  { id: "m01", text: "Notice your breath — without changing it.", sub: "Just observe. That's the whole thing." },
  { id: "m02", text: "Drop your shoulders just a little.", sub: "Notice if they rose back up. Let them drop again." },
  { id: "m03", text: "Unclench your jaw.", sub: "You probably didn't know it was clenched." },
  { id: "m04", text: "Feel your feet on the ground.", sub: "Wherever you are right now — floor, bed, bathroom tile." },
  { id: "m05", text: "Take one slower exhale.", sub: "Just one. That's enough." },
  { id: "m06", text: "Place a hand on your chest or stomach.", sub: "Notice what you feel under your hand." },
  { id: "m07", text: "Notice where you feel tension in your body.", sub: "You don't have to fix it. Just locate it." },
  { id: "m08", text: "Soften your forehead.", sub: "Let the space between your eyebrows go smooth." },
  { id: "m09", text: "Let your body be supported by something.", sub: "Chair, wall, bed, floor — let it hold you." },
  { id: "m10", text: "Ask yourself: Am I holding my breath right now?", sub: "If yes — let it go." },
  // ⚡ Catching Overwhelm Early
  { id: "m11", text: "Notice the first sign of frustration — before it becomes something bigger.", sub: "What does it feel like in your body right now?" },
  { id: "m12", text: "Ask: What do I actually need in the next hour?", sub: "Not what needs to happen. What do you need." },
  { id: "m13", text: "Check: Am I already rushing — and the day hasn't even started?", sub: "Notice it. You don't have to stop it yet." },
  { id: "m14", text: "Notice if your thoughts are already speeding ahead.", sub: "Can you bring them back to this room, this moment?" },
  // 💬 Inner Voice
  { id: "m15", text: "How are you speaking to yourself this morning?", sub: "Would you use that tone with someone you love?" },
  { id: "m16", text: "Replace 'I have to get through today' with 'I get to try again today.'", sub: "Small shift. Real difference." },
];

// ─── DAILY INVITATION PRACTICES ──────────────────────────────────────────────
// Observational, curious. A noticing — not a task.
// These live in the daytime card and rotate daily.

const INVITATION = [
  // 👶 Attuning to Baby
  { id: "i01", text: "Notice when your baby looks at you today. Really looks.", sub: "That's the whole practice." },
  { id: "i02", text: "Watch their eyebrows, eyes, and mouth for cues.", sub: "What are they telling you without words?" },
  { id: "i03", text: "Let yourself observe for 5 seconds before responding.", sub: "Just watch. Then move." },
  { id: "i04", text: "Notice their body — are they tense, floppy, arching?", sub: "Their body is always talking." },
  { id: "i05", text: "Ask: What is my baby trying to communicate — not control?", sub: "The reframe changes everything." },
  { id: "i06", text: "Notice what changes when you move closer or farther away.", sub: "You're already regulating them just by being near." },
  { id: "i07", text: "Make eye contact before doing anything else.", sub: "Connection first. Task second." },
  { id: "i08", text: "Mirror their expression gently.", sub: "Let your face say: I see you." },
  // 🧠 Shifting Perspective
  { id: "i09", text: "Ask: What else could be true right now?", sub: "The story you're telling yourself isn't the only one." },
  { id: "i10", text: "Notice the story you're telling yourself about today.", sub: "Is it accurate — or is it the exhaustion talking?" },
  { id: "i11", text: "Replace 'why is this happening' with 'what might be needed.'", sub: "One closes down. The other opens up." },
  { id: "i12", text: "Ask: Is this a problem — or a moment?", sub: "Not everything needs solving." },
  { id: "i13", text: "Notice if you're expecting something your baby can't give yet.", sub: "What's developmentally true for this age?" },
  { id: "i14", text: "Zoom out: Will this matter in a week?", sub: "If yes, it deserves your energy. If not — let it be smaller." },
  { id: "i15", text: "Notice one moment today where you felt like yourself.", sub: "Not a good parent. Just you." },
  { id: "i16", text: "What's one thing your baby did today that surprised you?", sub: "Big or small — just notice." },
  { id: "i17", text: "What would 'good enough' look like today?", sub: "Set the bar where you actually are." },
  // 🌊 Allowing
  { id: "i18", text: "Notice your urge to fix something that maybe just needs to be felt.", sub: "What if it didn't need solving right now?" },
  { id: "i19", text: "Let yourself be in the middle of something without needing to know the end.", sub: "This stage is temporary. You're in it anyway." },
  { id: "i20", text: "Notice what happens when you stop fighting the moment.", sub: "Even for 10 seconds." },
];

// ─── EVENING PRACTICES ───────────────────────────────────────────────────────
// Slowing down. Closing the loop. Before the sleep window opens.

const EVENING = [
  // 🌼 Tiny Moments of Stillness
  { id: "e01", text: "Look out a window for 10 seconds.", sub: "Let your eyes go soft. Let something else hold your attention." },
  { id: "e02", text: "Take a sip of something slowly.", sub: "Notice the warmth, the temperature, the taste." },
  { id: "e03", text: "Close your eyes for 3 seconds.", sub: "On purpose. Not avoidance — just rest." },
  { id: "e04", text: "Stretch your neck gently.", sub: "Tilt each ear toward its shoulder. Hold for a breath." },
  { id: "e05", text: "Let your body pause before the next task.", sub: "The next thing can wait 10 seconds." },
  { id: "e06", text: "Feel warm water on your hands.", sub: "Let that be the whole moment." },
  // ✨ Reconnection & Repair
  { id: "e07", text: "Notice if you need to repair anything from today.", sub: "It doesn't have to be big. A soft look. A touch. 'I'm here.'" },
  { id: "e08", text: "Let repair be simple — not perfect.", sub: "Connection doesn't need a speech. It needs presence." },
  { id: "e09", text: "Get down to your child's level before the sleep window.", sub: "Eyes at the same height. That matters." },
  { id: "e10", text: "Soften your eyes before your words tonight.", sub: "What your face says first is what they feel." },
  { id: "e11", text: "Offer touch — a hand, a hug, closeness.", sub: "Co-regulation through contact. Simple and real." },
  { id: "e12", text: "Remind yourself: repair matters more than getting it right.", sub: "You don't have to have been perfect today. You just have to show up now." },
  // 🌊 Allowing
  { id: "e13", text: "Let tonight be what it is — not what you need it to be.", sub: "Your nervous system will thank you." },
  { id: "e14", text: "Remind yourself: This can be hard and I can handle it.", sub: "Both things are true at once." },
  { id: "e15", text: "Allow the noise, the emotion — for just a few seconds.", sub: "You don't have to rush it away." },
  // 💛 Co-Regulation
  { id: "e16", text: "Take one slow breath while holding your baby.", sub: "Your exhale is their cue to settle." },
  { id: "e17", text: "Lower your voice by one level.", sub: "Slower, softer. Let them follow you down." },
  { id: "e18", text: "Let your movements become slower and more predictable.", sub: "Predictability is safety for their nervous system." },
  { id: "e19", text: "Hum or exhale audibly.", sub: "Sound is regulation. Let them hear you settle." },
  { id: "e20", text: "Let the goal be connection — not stopping the crying.", sub: "When connection comes first, the crying usually follows." },
];

// ─── LOG RESPONSE PRACTICES ──────────────────────────────────────────────────
// Triggered by what the parent just logged.
// These appear as a one-line nudge on the log confirmation screen.

// After logging something hard (rough night, short nap, won't settle, crying)
const LOG_HARD = {
  rough_night: [
    { id: "lh01", text: "Notice your shoulders right now.", sub: "Let them drop a little." },
    { id: "lh02", text: "Take one slower breath before the day starts.", sub: "You made it through the night." },
    { id: "lh03", text: "Ask: What do I need in the next 30 minutes?", sub: "Just that. Not the whole day." },
    { id: "lh04", text: "Feel your feet on the ground.", sub: "You're here. That's something." },
  ],
  short_nap: [
    { id: "lh05", text: "Pause before your next action — even for 3 seconds.", sub: "Notice the urge to 'fix this fast.'" },
    { id: "lh06", text: "Ask: What would slower look like here?", sub: "The answer might surprise you." },
    { id: "lh07", text: "Notice if your thoughts are speeding up.", sub: "That's your nervous system, not the truth." },
    { id: "lh08", text: "Unclench your jaw.", sub: "You probably didn't know it was clenched." },
  ],
  wont_settle: [
    { id: "lh09", text: "Pause and listen to the tone of their cry.", sub: "What is it telling you — not asking you to fix?" },
    { id: "lh10", text: "Notice their body — tense, floppy, arching?", sub: "Their body knows. Yours does too." },
    { id: "lh11", text: "Lower your voice by one level.", sub: "Let them follow you down." },
    { id: "lh12", text: "Name it quietly: 'I'm getting overwhelmed.'", sub: "Naming it is the first step out of it." },
  ],
  general_hard: [
    { id: "lh13", text: "Notice your breath — without changing it.", sub: "Just observe for one moment." },
    { id: "lh14", text: "Let your body be supported by something right now.", sub: "Chair, wall, floor — let it hold you." },
    { id: "lh15", text: "Ask: What is my baby communicating — not controlling?", sub: "The reframe changes everything." },
    { id: "lh16", text: "Remind yourself: This can be hard and I can handle it.", sub: "Both things are true." },
  ],
};

// After logging something good (good night, long nap, settled well)
// Follows the Notice → Body → Reflect → Identity → Anchor flow
const LOG_GOOD = [
  {
    id: "lg01",
    notice: "Wait — pause. That was different.",
    body: "Where do you feel that in your body right now?",
    reflect: "You stayed with them through that.",
    identity: "That's you showing up as a regulated parent.",
    anchor: "Take one breath and let that land.",
  },
  {
    id: "lg02",
    notice: "That moment is worth noticing.",
    body: "What feels different in your body compared to before?",
    reflect: "Your baby got to feel you stay steady.",
    identity: "That's the version of you you've been working toward.",
    anchor: "Let your body remember this.",
  },
  {
    id: "lg03",
    notice: "Don't rush past this one.",
    body: "Do you notice more softness, more space, more steadiness?",
    reflect: "You stayed instead of rushing — that's a real shift.",
    identity: "You're building a new way of responding.",
    anchor: "Can you take one slow breath and let that land?",
  },
  {
    id: "lg04",
    notice: "Something just shifted — did you feel it?",
    body: "What did your body do differently this time?",
    reflect: "They experienced you as steady there.",
    identity: "That wasn't luck — that was you.",
    anchor: "Stay with that feeling for one more second.",
  },
  {
    id: "lg05",
    notice: "That was you breaking a pattern in real time.",
    body: "What just shifted inside you?",
    reflect: "That moment builds trust, even if it felt small.",
    identity: "You're becoming someone who can stay in it.",
    anchor: "Let your nervous system record this.",
  },
];

// ─── NOTICED STATEMENTS ───────────────────────────────────────────────────────
// Held's observations — shown in the daily moment card below the streak bar.
// Rotate by day-of-week. Generated from real data in the app — these are
// templates; the actual numbers/words are filled in at render time.
// When no data exists yet, fall back to NOTICED_DEFAULT.

export const NOTICED_TEMPLATES = {
  // progress: fewer hard check-ins
  progress: (fewer, total) =>
    `You've felt overwhelmed less this week — ${fewer} check-in${fewer !== 1 ? "s" : ""} instead of ${total}. That's real movement, even if it doesn't feel like it yet.`,
  // consistency: they've been logging
  consistency: (days) =>
    `${days} days showing up. Most parents don't make it past three. Whatever's keeping you here — keep doing it.`,
  // pattern: something keeps coming up
  pattern: (topic, count) =>
    `${topic} keeps coming up for you — ${count} of your recent check-ins mention it. Your nervous system is paying attention.`,
  // hard_week: more rough nights than last
  hard_week: () =>
    `It's been a harder week than last. Worth naming — not fixing, just noticing. You're still here.`,
  // win: fewer rough nights
  win: (lastWeek, thisWeek) =>
    `Last week you had ${lastWeek} hard night${lastWeek !== 1 ? "s" : ""}. This week, ${thisWeek}. You probably don't feel the difference yet — but it's there.`,
  // showing_up: emotional labor
  showing_up: (count) =>
    `You've checked in ${count} time${count !== 1 ? "s" : ""} this week. Every one of those was a moment you chose yourself over the chaos.`,
};

export const NOTICED_DEFAULT =
  "Showing up — even on the hard days — is the practice. You're doing it.";

// ─── SELECTORS ───────────────────────────────────────────────────────────────

/**
 * getPractice(surface, nsState, seed)
 * Returns a single practice object for the given surface.
 *
 * @param {"morning"|"invitation"|"evening"} surface
 * @param {string|null} nsState  — parent's current NS state from check-in history
 * @param {number} seed          — use new Date().getDate() for daily rotation
 * @returns {{ id, text, sub }}
 */
export function getPractice(surface, nsState, seed = new Date().getDate()) {
  const pools = {
    morning:    MORNING,
    invitation: INVITATION,
    evening:    EVENING,
  };

  const pool = pools[surface] || INVITATION;

  // If parent is overwhelmed/activated, weight toward grounding practices
  // (those starting with m0x or e1x). Simple: pick from first half of pool.
  if (nsState === "overwhelmed" || nsState === "activated") {
    const groundingPool = pool.slice(0, Math.ceil(pool.length / 2));
    return groundingPool[seed % groundingPool.length];
  }

  // Default: rotate by seed (day of month keeps it stable all day, changes daily)
  return pool[seed % pool.length];
}

/**
 * getLogPractice(logType, isPositive, seed)
 * Returns a practice triggered by a specific log event.
 *
 * @param {"rough_night"|"short_nap"|"wont_settle"|"general_hard"} logType
 * @param {boolean} isPositive  — true for good log events
 * @param {number} seed
 * @returns {{ id, text, sub } | { id, notice, body, reflect, identity, anchor }}
 */
export function getLogPractice(logType, isPositive, seed = new Date().getDate()) {
  if (isPositive) {
    return LOG_GOOD[seed % LOG_GOOD.length];
  }

  const pool = LOG_HARD[logType] || LOG_HARD.general_hard;
  return pool[seed % pool.length];
}

/**
 * getNoticedStatement(patterns, familyState)
 * Returns the right "Held noticed" sentence based on real data.
 * Falls back to NOTICED_DEFAULT if no meaningful pattern exists.
 *
 * @param {object} patterns     — from useCheckinHistory()
 * @param {object} familyState  — from useFamilyState()
 * @param {number} seed         — day-of-week for rotation (0–6)
 * @returns {string}
 */
export function getNoticedStatement(patterns, familyState, seed = new Date().getDay()) {
  if (!patterns || patterns.total < 3) return NOTICED_DEFAULT;

  const options = [];

  // Progress: fewer hard check-ins this week vs last
  if (patterns.progressDelta !== null && patterns.progressDelta < -1) {
    options.push({
      type: "progress",
      text: NOTICED_TEMPLATES.progress(
        Math.abs(patterns.progressDelta),
        (patterns.total || 5)
      ),
    });
  }

  // Consistency: days showing up
  if (familyState?.daysShowingUp >= 5) {
    options.push({
      type: "consistency",
      text: NOTICED_TEMPLATES.consistency(familyState.daysShowingUp),
    });
  }

  // Pattern: hardest time keeps recurring
  if (patterns.hardestTime && patterns.hardestTimeCount >= 3) {
    options.push({
      type: "pattern",
      text: NOTICED_TEMPLATES.pattern(patterns.hardestTime, patterns.hardestTimeCount),
    });
  }

  // Hard week: more rough nights
  if (familyState?.sleepData?.consecutiveBadNights >= 3) {
    options.push({ type: "hard_week", text: NOTICED_TEMPLATES.hard_week() });
  }

  // Win: fewer rough nights this week vs last
  if (
    familyState?.sleepData?.lastWeekBadNights > 2 &&
    familyState?.sleepData?.thisWeekBadNights < familyState?.sleepData?.lastWeekBadNights
  ) {
    options.push({
      type: "win",
      text: NOTICED_TEMPLATES.win(
        familyState.sleepData.lastWeekBadNights,
        familyState.sleepData.thisWeekBadNights
      ),
    });
  }

  // Showing up: check-in count this week
  if (patterns.total >= 4) {
    options.push({
      type: "showing_up",
      text: NOTICED_TEMPLATES.showing_up(patterns.total),
    });
  }

  if (options.length === 0) return NOTICED_DEFAULT;

  // Rotate through available options by day-of-week
  // so it genuinely changes day to day when multiple apply
  return options[seed % options.length].text;
}
